import type { LadderExporter } from './types';
import type { LadderProject, LadderElement, ContactElement, CoilElement, TimerElement, CounterElement } from '../schema/types';
import { isContactElement, isCoilElement, isTimerElement, isCounterElement } from '../schema/types';

/**
 * Keyence KV Series Ladder Mnemonic Exporter
 *
 * Generates KV series ladder logic in mnemonic format.
 * Supports: LD, AND, OR, OUT, AND-NOT, OR-NOT, TMR, CNT
 *
 * Example output:
 * ; Project: Motor Control
 * ; Generated by Ladder Web IDE
 *
 * ; Rung 1
 * LD X0
 * AND X1
 * OUT Y0
 *
 * ; Rung 2
 * LD X2
 * TMR T0 1000
 */
export class KeyenceExporter implements LadderExporter {
  name = 'Keyence KV Series';
  vendor = 'keyence';
  fileExtension = '.kv';

  export(project: LadderProject): string {
    const lines: string[] = [];

    // Header comments
    lines.push(`; Project: ${project.name}`);
    lines.push(`; Generated by Ladder Web IDE`);
    lines.push(`; Date: ${new Date().toISOString()}`);
    lines.push('');

    // Process each rung
    project.rungs.forEach((rung, index) => {
      lines.push(`; Rung ${index + 1}`);
      if (rung.comment) {
        lines.push(`; ${rung.comment}`);
      }

      // Generate instructions for elements in this rung
      const instructions = this.generateRungInstructions(rung.elements);
      lines.push(...instructions);
      lines.push('');
    });

    return lines.join('\n');
  }

  private generateRungInstructions(elements: LadderElement[]): string[] {
    const instructions: string[] = [];
    let isFirstElement = true;

    // Sort elements by position for correct order
    const sortedElements = [...elements].sort((a, b) => a.position.x - b.position.x);

    for (const element of sortedElements) {
      if (isContactElement(element)) {
        instructions.push(...this.generateContactInstruction(element, isFirstElement));
        isFirstElement = false;
      } else if (isCoilElement(element)) {
        instructions.push(...this.generateCoilInstruction(element));
        isFirstElement = true; // Reset for next rung logic
      } else if (isTimerElement(element)) {
        instructions.push(...this.generateTimerInstruction(element));
        isFirstElement = true;
      } else if (isCounterElement(element)) {
        instructions.push(...this.generateCounterInstruction(element));
        isFirstElement = true;
      }
    }

    return instructions;
  }

  private generateContactInstruction(element: ContactElement, isFirst: boolean): string[] {
    const variable = this.formatVariable(element.variable);

    if (element.contactType === 'no') {
      // Normally Open contact
      if (isFirst) {
        return [`LD ${variable}`];
      } else {
        return [`AND ${variable}`];
      }
    } else {
      // Normally Closed contact
      if (isFirst) {
        return [`LD-NOT ${variable}`];
      } else {
        return [`AND-NOT ${variable}`];
      }
    }
  }

  private generateCoilInstruction(element: CoilElement): string[] {
    const variable = this.formatVariable(element.variable);

    switch (element.coilType) {
      case 'output':
        return [`OUT ${variable}`];
      case 'set':
        return [`SET ${variable}`];
      case 'reset':
        return [`RST ${variable}`];
      default:
        return [`OUT ${variable}`];
    }
  }

  private generateTimerInstruction(element: TimerElement): string[] {
    const variable = this.formatVariable(element.variable);
    // TMR T0 1000 (timer number, preset in 100ms units typically)
    // Convert ms to 100ms units (Keyence standard)
    const preset = Math.ceil(element.preset / 100);
    return [`TMR ${variable} ${preset}`];
  }

  private generateCounterInstruction(element: CounterElement): string[] {
    const variable = this.formatVariable(element.variable);
    // CNT C0 10 (counter number, preset)
    return [`CNT ${variable} ${element.preset}`];
  }

  /**
   * Format variable name for Keyence format
   * Keyence uses: X (inputs), Y (outputs), M (internal), T (timers), C (counters)
   */
  private formatVariable(variable: string): string {
    // Keep the variable as-is if it already has a proper prefix
    if (/^[XYMLTCD]\d+$/.test(variable)) {
      return variable;
    }

    // If no prefix, assume it's an internal bit (M)
    if (/^\d+$/.test(variable)) {
      return `M${variable}`;
    }

    return variable;
  }
}

// Singleton instance
export const keyenceExporter = new KeyenceExporter();
