import { describe, it, expect } from 'vitest';
import { KeyenceExporter } from './keyence';
import type { LadderProject } from '../schema/types';

describe('KeyenceExporter', () => {
  const exporter = new KeyenceExporter();

  it('should have correct metadata', () => {
    expect(exporter.name).toBe('Keyence KV Series');
    expect(exporter.vendor).toBe('keyence');
    expect(exporter.fileExtension).toBe('.kv');
  });

  it('should export empty project', () => {
    const project: LadderProject = {
      name: 'Empty Project',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [],
    };

    const output = exporter.export(project);
    expect(output).toContain('; Project: Empty Project');
    expect(output).toContain('Generated by Ladder Web IDE');
  });

  it('should export contact and coil', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [{
        id: 'rung-1',
        elements: [
          {
            id: 'contact-1',
            type: 'contact',
            variable: 'X0',
            contactType: 'no',
            position: { x: 0, y: 0 },
            connections: {},
          },
          {
            id: 'coil-1',
            type: 'coil',
            variable: 'Y0',
            coilType: 'output',
            position: { x: 1, y: 0 },
            connections: {},
          },
        ],
        position: 0,
      }],
    };

    const output = exporter.export(project);
    expect(output).toContain('LD X0');
    expect(output).toContain('OUT Y0');
  });

  it('should export NC contact with AND-NOT', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [{
        id: 'rung-1',
        elements: [
          {
            id: 'contact-1',
            type: 'contact',
            variable: 'X0',
            contactType: 'no',
            position: { x: 0, y: 0 },
            connections: {},
          },
          {
            id: 'contact-2',
            type: 'contact',
            variable: 'X1',
            contactType: 'nc',
            position: { x: 1, y: 0 },
            connections: {},
          },
          {
            id: 'coil-1',
            type: 'coil',
            variable: 'Y0',
            coilType: 'output',
            position: { x: 2, y: 0 },
            connections: {},
          },
        ],
        position: 0,
      }],
    };

    const output = exporter.export(project);
    expect(output).toContain('LD X0');
    expect(output).toContain('AND-NOT X1');
    expect(output).toContain('OUT Y0');
  });

  it('should export set coil with SET', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [{
        id: 'rung-1',
        elements: [
          {
            id: 'contact-1',
            type: 'contact',
            variable: 'X0',
            contactType: 'no',
            position: { x: 0, y: 0 },
            connections: {},
          },
          {
            id: 'coil-1',
            type: 'coil',
            variable: 'Y0',
            coilType: 'set',
            position: { x: 1, y: 0 },
            connections: {},
          },
        ],
        position: 0,
      }],
    };

    const output = exporter.export(project);
    expect(output).toContain('SET Y0');
  });

  it('should export reset coil with RST', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [{
        id: 'rung-1',
        elements: [
          {
            id: 'contact-1',
            type: 'contact',
            variable: 'X0',
            contactType: 'no',
            position: { x: 0, y: 0 },
            connections: {},
          },
          {
            id: 'coil-1',
            type: 'coil',
            variable: 'Y0',
            coilType: 'reset',
            position: { x: 1, y: 0 },
            connections: {},
          },
        ],
        position: 0,
      }],
    };

    const output = exporter.export(project);
    expect(output).toContain('RST Y0');
  });

  it('should export TON timer with TMR', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [{
        id: 'rung-1',
        elements: [
          {
            id: 'contact-1',
            type: 'contact',
            variable: 'X0',
            contactType: 'no',
            position: { x: 0, y: 0 },
            connections: {},
          },
          {
            id: 'timer-1',
            type: 'timer',
            variable: 'T0',
            timerType: 'TON',
            preset: 1000,
            position: { x: 1, y: 0 },
            connections: {},
          },
        ],
        position: 0,
      }],
    };

    const output = exporter.export(project);
    // Timer preset is converted to 100ms units (1000ms -> 10)
    expect(output).toContain('TMR T0 10');
  });

  it('should export counter with CNT', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [{
        id: 'rung-1',
        elements: [
          {
            id: 'contact-1',
            type: 'contact',
            variable: 'X0',
            contactType: 'no',
            position: { x: 0, y: 0 },
            connections: {},
          },
          {
            id: 'counter-1',
            type: 'counter',
            variable: 'C0',
            counterType: 'CTU',
            preset: 10,
            position: { x: 1, y: 0 },
            connections: {},
          },
        ],
        position: 0,
      }],
    };

    const output = exporter.export(project);
    expect(output).toContain('CNT C0 10');
  });

  it('should export multiple rungs with comments', () => {
    const project: LadderProject = {
      name: 'Test',
      version: '1.0',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      rungs: [
        {
          id: 'rung-1',
          comment: 'Start motor',
          elements: [
            {
              id: 'contact-1',
              type: 'contact',
              variable: 'X0',
              contactType: 'no',
              position: { x: 0, y: 0 },
              connections: {},
            },
            {
              id: 'coil-1',
              type: 'coil',
              variable: 'Y0',
              coilType: 'output',
              position: { x: 1, y: 0 },
              connections: {},
            },
          ],
          position: 0,
        },
        {
          id: 'rung-2',
          comment: 'Stop motor',
          elements: [
            {
              id: 'contact-2',
              type: 'contact',
              variable: 'X1',
              contactType: 'no',
              position: { x: 0, y: 0 },
              connections: {},
            },
            {
              id: 'coil-2',
              type: 'coil',
              variable: 'Y0',
              coilType: 'reset',
              position: { x: 1, y: 0 },
              connections: {},
            },
          ],
          position: 1,
        },
      ],
    };

    const output = exporter.export(project);
    // Comments appear on separate line after rung number
    expect(output).toContain('; Rung 1');
    expect(output).toContain('; Start motor');
    expect(output).toContain('; Rung 2');
    expect(output).toContain('; Stop motor');
  });
});
